---

- name: created OS group lumis
  group:
    name: "{{ lumis_group }}"
    state: present

- name: created OS user lumis
  user:
    name: "{{ lumis_user }}"
    state: present
    group: "{{ lumis_group }}"
    createhome: false
    system: true

- name: defined variable lumis version
  set_fact:
    lumis_version: "{{ __lumis_version }}"
  when: lumis_version is not defined

- name: defined variable lumis release
  set_fact:
    lumis_release: "{{ __lumis_release }}"
  when: lumis_release is not defined

- name: install lumis if Redhat OS
  yum:
    name: "{{ packages }}"
    state: present
  when: ansible_os_family == 'RedHat'

- include_tasks: install.yml
