---

- name: copied mysql connector java
  copy:
    src: files/mysql-connector-java-8.0.17.jar
    dest: "{{ lumis_directory }}/{{ lumis_name }}/www/WEB-INF/lib"
    owner: "{{ lumis_user }}"
    group: "{{ lumis_group  }}"
    mode: 0755
  tags:
    - lumisportal
    - bootstrap

- name: created a database
  mysql_db:
    name: "{{ lumis_db_name }}"
    state: present
    login_host: "{{ lumis_db_url }}"
    login_password: "{{ lumis_db_pass }}"
    login_port: "{{ lumis_db_port }}"
    login_user: "{{ lumis_db_user }}"
  register: shouldToExistDatabase
  when: inventory_hostname == "lumis1"
  tags:
    - lumisportal
    - bootstrap

- name: verified if database was created
  command: mysql -h "{{ lumis_db_url }}" -u "{{ lumis_db_user }}" -p"{{ lumis_db_pass }}"  -NBe "SELECT count(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='lum_Principal'"
  register: lum_Principal_already_exists
  changed_when: false
  check_mode: false
  when: inventory_hostname == "lumis1"
  tags:
    - lumisportal
    - bootstrap

- name: imported tables and datas
  mysql_db:
    state: import
    name: "{{ lumis_db_name }}"
    target: "{{ lumis_directory }}/{{ lumis_name }}/setup/db_mysql.sql"
    login_host: "{{ lumis_db_url }}"
    login_password: "{{ lumis_db_pass }}"
    login_port: "{{ lumis_db_port }}"
    login_user: "{{ lumis_db_user }}"

  when: inventory_hostname == "lumis1" and lum_Principal_already_exists.stdout == "0"
  tags:
    - lumisportal
    - bootstrap

- name: initialized Portal
  command: "./initializeportal.sh"
  args:
    chdir: "{{ lumis_directory }}/{{ lumis_name }}/setup/"
  become: yes
  become_user: "{{ lumis_user }}"
  when: inventory_hostname == "lumis1" and lum_Principal_already_exists.stdout == "0"
  tags:
    - lumisportal
    - bootstrap

- name: copied default configuration MySQL
  template:
    src: MySQL.sql.j2
    dest: "{{ lumis_directory }}/{{ lumis_name }}/setup/MySQL.sql"
    owner: "{{ lumis_user }}"
    group: "{{ lumis_group  }}"
    mode: 0755
  notify: restart tomcat
  when: inventory_hostname == "lumis1" and lum_Principal_already_exists.stdout == "0"
  tags:
    - lumisportal
    - bootstrap

- name: imported default configuration MySQL
  mysql_db:
    state: import
    name: "{{ lumis_db_name }}"
    target: "{{ lumis_directory }}/{{ lumis_name }}/setup/MySQL.sql"
    login_host: "{{ lumis_db_url }}"
    login_password: "{{ lumis_db_pass }}"
    login_port: "{{ lumis_db_port }}"
    login_user: "{{ lumis_db_user }}"
  when: inventory_hostname == "lumis1" and lum_Principal_already_exists.stdout == "0"
  tags:
    - skip_ansible_lint
    - lumisportal
    - bootstrap
