---
- name: Copy mysql connector java
  copy:
    src: files/mysql-connector-java-8.0.17.jar
    dest: "{{ lumis_directory }}/{{ lumis_name }}/www/WEB-INF/lib"
    owner: "{{ lumis_user }}"
    group: "{{ lumis_group  }}"
    mode: 0755

- name: Force create a database for Lumis framework
  mysql_db:
    name: "{{ lumis_db_name }}"
    state: present
  register: shouldToExistDatabase

- name: Verify if database was created
  command: mysql -NBe "SELECT count(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='lum_Principal'"
  register: lum_Principal_already_exists
  changed_when: false
  check_mode: false

- name: Display all variables/facts known for a host
  debug:
    var: lum_Principal_already_exists

- name: Import db_mysql.sql
  mysql_db:
    state: import
    name: "{{ lumis_db_name }}"
    target: "{{ lumis_directory }}/{{ lumis_name }}/setup/db_mysql.sql"
    login_host: "{{ lumis_db_url }}"
    login_password: "{{ lumis_db_pass }}"
    login_port: "{{ lumis_db_port }}"
    login_user: "{{ lumis_db_user }}"
  when: lum_Principal_already_exists.stdout == "0"
  tags:
    - skip_ansible_lint

- name: Initialize Portal
  command: "./initializeportal.sh"
  args:
    executable: /bin/bash
    chdir: "{{ lumis_directory }}/{{ lumis_name }}/setup/"
  when: lum_Principal_already_exists.stdout == "0"
  tags:
    - skip_ansible_lint

- name: Copy default configuration MySQL
  template:
    src: MySQL.sql.j2
    dest: "{{ lumis_directory }}/{{ lumis_name }}/setup/MySQL.sql"
    owner: "{{ lumis_user }}"
    group: "{{ lumis_group  }}"
    mode: 0755
  when: lum_Principal_already_exists.stdout == "0"
  notify: restart tomcat

- name: Import default configuration MySQL
  mysql_db:
    state: import
    name: "{{ lumis_db_name }}"
    target: "{{ lumis_directory }}/{{ lumis_name }}/setup/MySQL.sql"
    login_host: "{{ lumis_db_url }}"
    login_password: "{{ lumis_db_pass }}"
    login_port: "{{ lumis_db_port }}"
    login_user: "{{ lumis_db_user }}"
  when: lum_Principal_already_exists.stdout == "0"
  tags:
    - skip_ansible_lint
