---
- name: Converge
  hosts: all
  become: true

  vars:
    zulu_version: 11
    zulu_release: 11.39.15
    zulu_jdk_version: jdk11.0.7
    java_home: /usr/lib/jvm/zulu-{{ zulu_version }}

  environment:
    JAVA_HOME: "{{ java_home }}"

  roles:
    - role: jeduoliveira.zulu_openjdk
    - role: jeduoliveira.elasticsearch
    - role: jeduoliveira.tomcat
    - role: geerlingguy.mysql
      mysql_databases:
        - name: lumisportal
          encoding: latin1
          collation: latin1_general_ci
      mysql_enabled_on_startup: true
      mysql_root_password_update: true
      mysql_root_password: 123456789
      mysql_users:
        - name: lumisportal
          host: "%"
          password: 123456789
          priv: "lumisportal.*:ALL"

    - role: ansible-role-lumisportal
