---
name: Molecule Test
on: [push, pull_request]
jobs:
    build:
        runs-on: alpine-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.7]

        steps:
            - uses: actions/checkout@v2
              with:
                path: roles
            
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Install dependencies
              run: |
                sudo apt install docker
               
                python3 -m pip install --upgrade pip
                python3 -m pip install  "molecule[ansible,docker,lint]"
            
            - name: Test with molecule
              run: |
                cd roles && molecule test